Task1();
b();
c('error');
createHeaders(5);
console.log("Task 4:");
console.log(checkPass("Web"));
console.log(checkPass("C++"));
console.log("Task 5:");
console.log(signNum(-5));
console.log("Task 6:");
console.log(days(3));